return PlaceObj('ModDef', {
	'title', "Vanilla Weapons Expanded",
	'description', '[h1]Vanilla Weapons Expanded[/h1]\n[h2]Overview[/h2]\nExpands over the vanilla weapons adding more components slots, ammo, combat actions\n[h3]Affected items[/h3]\n[list]\n    [*]Unarmed and Unarmed Infected (now can be scrapped)\n    [*]M24 (added side2 and side3 slots)\n    [*]AA12 (added side2 and side3 slots)\n    [*]MG42 (added muzzle and barrel slots)\n    [*]M16, M14, Galil, G36, PSG1, M4, M41 (added side2 slot)\n    [*]BarretM82 (added side slot)\n    [*]Almost all core components\n    [*]All affected items retain the same status as the vanilla (damage, bonuses, damage) except for one item, Tactical Device, now no longer illuminates the wielder but only illuminates the target at 3+ aim\n[/list]\n[h3][i]Ammo changes[/i][/h3]\n[list]\n    [*]All tracer ammo adds "range modifier +1" for small caliber "+2" for large ones\nnew ammo\n    [*]Incendiary versions of 40mm grenade and mortar shell (sound effects are the same as molotov because I don\'t know how to change it)\n[/list]\n[h3][i]Combat actions[/i][/h3]\n- Almost all weapons now can use "unarmed" (it enables unarmed attacks because doesn\'t makes sense to me that you can\'t hit someone with the stock of your weapon, the aim animation looks like a point blank shot, but it will deliver a punch)\n[hr][/hr]\n[h3]Related Mods[/h3]\n[list]\n	[*][url=https://steamcommunity.com/sharedfiles/filedetails/?id=3238572469] Vanilla Weapons Expanded - Quest Items [/url]\n	[*][url=https://steamcommunity.com/sharedfiles/filedetails/?id=3238744119] Enhanced Kompositum [/url]\n[/list]',
	'image', "Mod/WeaponsExpanded/Images/Screenshot 2024-04-08 161609.jpg",
	'external_links', {
		"https://github.com/yasumitsu/Vanilla-Weapons-Expanded",
	},
	'last_changes', "- added slug to shotguns",
	'id', "WeaponsExpanded",
	'author', "Sir Ni",
	'version_major', 2,
	'version', 291,
	'lua_revision', 233360,
	'saved_with_revision', 350233,
	'code', {
		"InventoryItem/Unarmed.lua",
		"InventoryItem/_9mm_Tracer.lua",
		"InventoryItem/_762NATO_Tracer.lua",
		"InventoryItem/_40mmIncendiaryGrenade.lua",
		"InventoryItem/AR15.lua",
		"InventoryItem/Winchester1894.lua",
		"InventoryItem/HK21.lua",
		"InventoryItem/MP5.lua",
		"InventoryItem/M24Sniper.lua",
		"InventoryItem/AA12.lua",
		"InventoryItem/UZI.lua",
		"InventoryItem/MG42.lua",
		"InventoryItem/Bereta92.lua",
		"InventoryItem/M16A2.lua",
		"InventoryItem/DesertEagle.lua",
		"InventoryItem/M14SAW.lua",
		"InventoryItem/ColtAnaconda.lua",
		"InventoryItem/Galil.lua",
		"InventoryItem/FNFAL.lua",
		"InventoryItem/AUG.lua",
		"InventoryItem/G36.lua",
		"InventoryItem/PSG1.lua",
		"InventoryItem/AK74.lua",
		"InventoryItem/M4Commando.lua",
		"InventoryItem/M41Shotgun.lua",
		"InventoryItem/FAMAS.lua",
		"InventoryItem/BarretM82.lua",
		"InventoryItem/DragunovSVD.lua",
		"InventoryItem/MortarShell_Incendiary.lua",
		"InventoryItem/_762WP_Tracer.lua",
		"InventoryItem/Unarmed_Infected.lua",
		"InventoryItem/_556_Tracer.lua",
		"InventoryItem/FNFiveSeven.lua",
	},
	'default_options', {},
	'has_data', true,
	'saved', 1720085664,
	'code_hash', 8092167892923632564,
	'affected_resources', {
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "FlashlightDot_PSG_M1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Flashlight_PSG_M1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "LaserDot_PSG_M1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "UVDot_PSG_M1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "FlashlightDot_aa12",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "UVDot_aa12",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "LaserDot_aa12",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "LaserDot_Anaconda",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "UVDot_Anaconda",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "FlashlightDot_Anaconda",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BarrelNormal",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BarrelLongShotgun",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BarrelHeavy",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BarrelLong",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BarrelLongImproved",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BarrelNormalImproved",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BarrelShort",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BarrelShortImproved",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BarrelShort_Winchester",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Galil_Handguard_Default",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "GrenadeLauncher_Galil",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Galil_Brake_Default",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MagLarge",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MagLargeFine",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MagNormal",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MagNormalFine",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MagQuick",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ImprovisedSuppressor",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Suppressor",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Compensator",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Compensator_Glock",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MuzzleBooster_Glock18",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "GrenadeLauncher",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ReflexSightAdvanced_Glock",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G36ReflexScope",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "AUGScope_Default",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "PSG_DefaultScope",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G36ThermalScope",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "LROptics",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "LROpticsAdvanced",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ReflexSight",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ReflexSightAdvanced",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ScopeCOG",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ScopeCOGQuick",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ThermalScope",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "StockNormal",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "StockHeavy",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "StockLight",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "Unarmed",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_9mm_Tracer",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_762NATO_Tracer",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_40mmIncendiaryGrenade",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "AR15",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "Winchester1894",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "HK21",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "MP5",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "M24Sniper",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "AA12",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "UZI",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "MG42",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "Bereta92",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "M16A2",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "DesertEagle",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "M14SAW",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "ColtAnaconda",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "Galil",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "FNFAL",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "AUG",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "G36",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "PSG1",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "AK74",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "M4Commando",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "M41Shotgun",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "FAMAS",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "BarretM82",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "DragunovSVD",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "MortarShell_Incendiary",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_762WP_Tracer",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "Unarmed_Infected",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_556_Tracer",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "FNFiveSeven",
			'ClassDisplayName', "Inventory item",
		}),
	},
	'steam_id', "3239859485",
	'TagWeapons&Items', true,
})